version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: sudo npm i -g codecov
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: cat ./coverage/lcov.info | codecov
      - store_artifacts:
          path: dist
          destination: fetch/dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
